### ISSUE TITLE
Handle Assertion Errors

### ISSUE THREAD

**Issue by hf-kklein** [Hochfrequenz/rebdhuhn#39]
I know those are failing, but there is no meaningful error message (see Hochfrequenz/ebdtable2graph#35)

- [ ] E_0205
- [ ] E_0207
- [ ] E_0208
- [ ] E_0256
- [x] E_0404 => Hochfrequenz/ebddocx2table#92 
- [ ] E_0441
- [ ] E_0442
- [ ] E_0443
- [ ] E_0444
- [x] E_0459 => Hochfrequenz/ebdtable2graph#99 
- [x] E_0462 => Hochfrequenz/ebdtable2graph#105 
- [ ] E_0475
- [ ] E_0476
- [ ] E_0477
- [ ] E_0478
- [ ] E_0479
- [ ] E_0487
- [ ] E_0490
- [ ] E_0496
- [ ] E_0501
- [ ] E_0504
- [ ] E_0505
- [ ] E_0506
- [ ] E_0800
- [ ] E_0900

**Comment by lord-haffi** [comment]
I don't know how much of them are "Graph too complex", but this is better explained in #100. They are not supported by the plantuml conversion pipeline.

**Comment by OLILHR** [comment]
veraltet
